# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: 336151728602.dkr.ecr.us-west-2.amazonaws.com/argo-voting-app/vote
  tag: latest

redis:
  usePassword: false

replicaCount: 1
