postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: new-updates-ad62fb5
vote:
  image:
    tag: SA-147-update-vote-b-33b8a0c
worker:
  image:
    tag: latest
